// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Owner     string
	Currency  string
	CreatedAt pgtype.Timestamptz
	Balance   int64
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be -ve or +ve
	Amount    int64
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be +ve
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
