name: Run unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: dev-env

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: ${{secrets.DB_USER}}
          POSTGRES_DB: ${{secrets.DB_NAME}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.24
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install goose migration tool.
        uses: mscno/setup-goose@v1
        with:
          version: v3.24.1

      - name: Run migrations
        run: goose -dir ${{ secrets.GOOSE_MIGRATION_DIR }} postgres ${{ secrets.DB_SOURCE }} up

      - name: Test
        run: go test -v -cover -count=1 ./...